import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Providers from '@/components/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br" className='bg-neutral-50'>
      <body className={inter.className} >
        <Providers>
          <Navbar />
          <div className="container h-full pt-3">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}
